### ISSUE TITLE
how to use without losing js autocomplete

### ISSUE THREAD

**Issue by niradler** [mongodb-js/ace-autocompleter#7]
hi im using native js autocomplete, when i'm adding the Mongo autocomplete i'm losing the js autocomplete any idea how to keep them both ?

**Comment by imlucas** [comment]
@niradler Hopefully you have this sorted. Just a heads up as I ran into a similar issue with highlighting rules being overridden (published in `mongodb-ace-mode@0.3.0`) https://github.com/mongodb-js/ace-mode/commit/90bed15aab9b03453a8c73d91f400cbfe95256a9
